### PR TITLE
Update: Replace some assets with improved background images

### PR DESCRIPTION
**Pull request by 2TallTyler**
Some of the store assets are of a game with bumpy tracks, a station with disconnected platforms, and not much else. (No offense to whoever created them; I'm sure they had more important things to do!)

I think an upgrade is in order. 😃 

(I used Photoshop to crop the screenshots ~~because I'm a bad open-source user~~ so there aren't any .xcf files.

### CODE REVIEW

**Comment by TrueBrain** [comment]
Two questions:

- Are these screenshots based on a game of your own?
- Are the graphics used the default OpenGFX without any other GRFs loaded?

Mainly asking of license purposes :)

**Comment by 2TallTyler** [comment]
Yes and yes! :)

**Comment by TrueBrain** [comment]
Sorry for the delay, finally had time to look at this.

The lack of source files is a bit annoying, as that means nobody can make adjustments to them. This is the reason we have been using GIMP (and xcf files), so if some minor touchups are needed, anyone can do it.

Could I ask you to do this with GIMP and supply the XCF files? Or otherwise, can you supply the background images (without the logo etc), and I can take care of that.

**Comment by 2TallTyler** [comment]
I don't think I have the background images saved without the logos. I also appear to have lost the savegame. (I know, what a failure 😱).

The only way I could do this would be to create a new savegame and start over — which I'm willing to do if it's important to have the xcf files. I'm working on an entry for the title game competition anyway so I could do it as part of that.

**Comment by TrueBrain** [comment]
Well, I guess you made case and point, as you already lost the source material :D

Please don't forget to use layers in GIMP; check current XCFs on what I mean. This avoids the current issue of not having source material anymore :)

Tnx, we will await a new version of the images :D

**Comment by 2TallTyler** [comment]
@TrueBrain I managed to recover my source files and they now include .xcf files! Ready for re-review. 🙂

**Comment by TrueBrain** [comment]
Cheers! Much appreciated!

Replacing the images on GOG is a hassle, as we cannot do that ourselves, and I need to ask GOG. The Steam ones I will update with the next 13 release.

**Review by TrueBrain — APPROVED** [review]

**Pull request merged**
